manifest:
  remotes:
    - name: ddpdoj
      url-base: https://github.com/ddpdoj
  projects:
    - name: zmk
      remote: ddpdoj
      revision: nice-view-custom-screen
      import: app/west.yml
  self:
    path: config
