manifest:
  remotes:
    - name: ddpdoj
      url-base: https://github.com/ddpdoj
  projects:
    - name: zmk
      remote: ddpdoj
      revision: workflow/metadata-build
      import: app/west.yml
  self:
    path: config
